### PR TITLE
Fix failing multiple writes to same (missing) directory

### PR DESCRIPTION
**Pull request by atamon**

### CODE REVIEW

**Comment by solsson** [comment]
> Cant we add a dummy file to avoid the need for mkdir?

Git would have to create the folder world-writable for it to work regardless of docker environment, can it do that? I was dreaming of something like Kubernetes' [emptyDir](http://kubernetes.io/docs/user-guide/volumes/#emptydir) to mount a temporary volume.

I think the most simple solution would be to omit `VOLUME /svn` from the Dockerfile and run `chown daemon /svn` during docker build. But having /svn persistent is rather essential in production, and I'm not sure what it means to not have a volume declared.

**Comment by atamon** [comment]
build-contract completes for me now. We should go ahead and merge and release a new version of this soon.

**Comment by solsson** [comment]
Great pioneering work with build-contract. Works great, except maybe the reliance on latest rweb source in ../../rweb.

I'm getting a test error "done() invoked with non-Error":

```
rweb_1    | 172.27.0.3 -  19/Sep/2016:18:55:18 +0000 "POST /svn/lean-data/" 200
svn_1     | 172.27.0.4 - test [19/Sep/2016:18:55:18 +0000] "POST /svn/lean-data/?rweb=e.mkdir HTTP/1.1" 200 782
svn_1     | 172.27.0.2 - test [19/Sep/2016:18:55:20 +0000] "HEAD /svn/lean-data/?serv=json HTTP/1.1" 200 -
svn_1     | 172.27.0.2 - test [19/Sep/2016:18:55:20 +0000] "DELETE /svn/lean-data/!svn/txn/1-4 HTTP/1.1" 404 224
svn_1     | [Mon Sep 19 18:55:20.123015 2016] [dav:error] [pid 10:tid 140482961151744] [client 172.27.0.2:38298] Could not fetch resource information.  [404, #0]
svn_1     | [Mon Sep 19 18:55:20.123043 2016] [dav:error] [pid 10:tid 140482961151744] [client 172.27.0.2:38298] Named transaction doesn't exist.  [404, #175002]
rweb_1    | 172.27.0.3 -  19/Sep/2016:18:55:19 +0000 "POST /svn/lean-data/" 200
svn_1     | 172.27.0.4 - test [19/Sep/2016:18:55:18 +0000] "POST /svn/lean-data/?rweb=e.mkdir HTTP/1.1" 200 782
client_1  | { id: 5,
client_1  |   error: 
client_1  |    { log: [ [Object] ],
client_1  |      result: 'Committing transaction...\nsvn: E160024: Conflict at \'/081ab5e4-eca1-495c-a80f-b6c1835f4921\'',
client_1  |      operation: 'import',
client_1  |      message: 'Yolean Rowdata add folder',
client_1  |      successful: false,
client_1  |      revision: null,
client_1  |      output: 'Committing transaction...\nsvn: E160024: Conflict at \'/081ab5e4-eca1-495c-a80f-b6c1835f4921\'',
client_1  |      description: null,
client_1  |      target: '/081ab5e4-eca1-495c-a80f-b6c1835f4921',
client_1  |      nexturl: 'http://svn/svn/lean-data/',
client_1  |      headline: null,
client_1  |      summary: null } }
client_1  |     1) should support writing several files to the same (missing) folder
client_1  | 
client_1  | 
client_1  |   0 passing (2s)
client_1  |   1 failing
client_1  | 
svn_1     | 172.27.0.2 - test [19/Sep/2016:18:55:20 +0000] "HEAD /svn/lean-data/?serv=json HTTP/1.1" 200 -
client_1  |   1) repos-upload should support writing several files to the same (missing) folder:
client_1  |      Error: done() invoked with non-Error: {"id":5,"error":{"log":[{"result":"Committing transaction...\nsvn: E160024: Conflict at '/081ab5e4-eca1-495c-a80f-b6c1835f4921'","operation":"import","message":"Yolean Rowdata add folder","successful":false,"revision":null,"output":"Committing transaction...\nsvn: E160024: Conflict at '/081ab5e4-eca1-495c-a80f-b6c1835f4921'","description":null}],"result":"Committing transaction...\nsvn: E160024: Conflict at '/081ab5e4-eca1-495c-a80f-b6c1835f4921'","operation":"import","message":"Yolean Rowdata add folder","successful":false,"revision":null,"output":"Committing transaction...\nsvn: E160024: Conflict at '/081ab5e4-eca1-495c-a80f-b6c1835f4921'","description":null,"target":"/081ab5e4-eca1-495c-a80f-b6c1835f4921","nexturl":"http://svn/svn/lean-data/","headline":null,"summary":null}}
client_1  |       at Promise.all.then.catch.err (index.js:34:9)
client_1  |       at process._tickCallback (internal/process/next_tick.js:103:7)
client_1  | 
client_1  | 
client_1  | 
svn_1     | [Mon Sep 19 18:55:20.270645 2016] [dav:error] [pid 9:tid 140483011507968] [client 172.27.0.2:38302] Could not fetch resource information.  [301, #0]
svn_1     | [Mon Sep 19 18:55:20.270714 2016] [dav:error] [pid 9:tid 140483011507968] [client 172.27.0.2:38302] Requests for a collection must have a trailing slash on the URI.  [301, #175002]
svn_1     | 172.27.0.2 - test [19/Sep/2016:18:55:20 +0000] "HEAD /svn/lean-data/081ab5e4-eca1-495c-a80f-b6c1835f4921?serv=json HTTP/1.1" 301 -
```

**Comment by solsson** [comment]
Confirmed with build-contract on my side too.

**Pull request merged**
